version: "3.8"

services:
    client:
        image: crew-client:dev
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ".:/frontend"
            - "/app/frontend/node_modules"
        ports:
            - "3001:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
    server:
        image: crew-server:dev
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ".:/backend"
            - "/app/backend/node_modules"
        ports:
            - "3002:3001"
        # environment:
        #   - DB_CONNECTION_URL=
        #   - GOOGLE_AUTH_CLIENT_ID=
        #   - GOOGLE_AUTH_CLIENT_SECRET=
        #   - TOKEN_SECRET=
        #   - REFRESH_TOKEN_SECRET=
