version: "3.8"

services:
    client:
        image: crew-client:prod
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - "1387:80"
    server:
        image: crew-server:prod
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"
        environment:
        - NODE_ENV=production
    #   - DB_CONNECTION_URL=
    #   - GOOGLE_AUTH_CLIENT_ID=
    #   - GOOGLE_AUTH_CLIENT_SECRET=
    #   - TOKEN_SECRET=
    #   - REFRESH_TOKEN_SECRET=
