FROM node:15.11.0-alpine3.10 as build
WORKDIR /app/backend
COPY . /app/backend
RUN npm ci --only=prod --silent 
RUN npm install pm2 -g --silent 

CMD ["pm2-runtime", "start", "npm", "--", "run", "safestart"]
